### ISSUE TITLE
CSS làm vỡ hình ảnh

### ISSUE THREAD

**Issue by thangtranse** [thphuong204/Draft#1]
https://github.com/thphuong204/Draft/blob/0225ab2c91b2304a63a06400536dc931e6945bfb/styles.css#L101

cách khắc phục:

```css
#working>ul>div>li>.logo{
    width: 7vw;
    height: auto;
    border: none;
    border-radius: 10px;
}
```

Dựa vào css trên, mình muốn cố định kích thước theo chiều nào thì gán cứng giá trị ứng với chiều đó và giá trị còn lại để `auto`
