### ISSUE TITLE
CSS làm ảnh hưởng đến responsive

### ISSUE THREAD

**Issue by thangtranse** [thphuong204/Draft#2]
https://github.com/thphuong204/Draft/blob/0225ab2c91b2304a63a06400536dc931e6945bfb/styles.css#L42

```css
#about-me .general>.card {
    display: flex;
    flex-direction: column;
    background-color: #f7f5e9;
    border:#f7f5e9;
    color:#434242;
    align-items: center;
}
```

Nên hạn chế sử dụng `width` với các thẻ tag của getBootstrap
